# .ps_project/config.yaml:

version: 2

workflows:
  experiment-workflow:
    steps:
      -
        name: "rigl-mnist-grad-accumulation-1"
        command: experiment.run_single_node
        params:
          command: python train_mnist_rigl.py
          container: pytorch/pytorch:latest
          experimentEnv:
            # DENSE_ALLOCATION: 0.1
            # STATIC_TOPO: 0
            # DELTA: 100
            # ALPHA: 0.3
            # GRAD_ACCUMULATION_N: 1
            EPOCHS: 14
            # LR: 1.0
            # GAMMA: 0.7
            BATCH_SIZE: 64
            EVAL_BATCH_SIZE: 1000
          machineType: P4000
          modelPath: /artifacts
          modelType: Tensorflow
          name: rigl-mnist-cli-config-yaml
      triggers:
        branches:
          only: paperspace
