version: 2
workflows:
  experiment-workflow:
    triggers:
      branches:
        only: master
    steps:
      -
        name: "rigl-mnist-grad-accumulation-1"
        command: experiment.run_single_node
        params:
          command: python train_mnist_rigl.py
          container: pytorch/pytorch:latest
          experimentEnv:
            EPOCHS: 14
            BATCH_SIZE: 64
            EVAL_BATCH_SIZE: 1000
          machineType: P4000
          modelPath: /artifacts
          modelType: Tensorflow
          name: rigl-mnist-cli-config-yaml
